services:
  minio:
    image: minio/minio:RELEASE.2024-07-31T05-46-26Z.fips
    container_name: minio
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
      - MINIO_DEFAULT_BUCKETS=${AWS_BUCKET_NAME}
    volumes:
      - minio_data:/data
    expose:
      - "9000"
      - "9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    hostname: minio
    command: server /data --console-address ":9001"

  uploader:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: uploader
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_URI=http://minio:9000
      - MINIO_ALIAS=${MINIO_ALIAS:-minioserver}
      - UNZIP_DATASET=true
    depends_on:
      - minio
    volumes:
      - ./run.sh:/home/kaggle/run.sh
    entrypoint: ["bash", "run.sh"]

volumes:
  minio_data:
